import { LoaderCircle, Search, X } from 'lucide-react';

export function Button({ children, variant = 'primary', className = '', type = 'button', ...props }) {
  const styles = { primary: 'bg-teal-600 text-white hover:bg-teal-700', secondary: 'border border-navy-100 bg-white text-navy-700 hover:bg-navy-50', ghost: 'text-navy-700 hover:bg-navy-50', danger: 'bg-danger text-white hover:bg-red-700' };
  return <button type={type} className={`inline-flex min-h-11 items-center justify-center gap-2 rounded-lg px-5 font-bold transition-colors disabled:cursor-not-allowed disabled:opacity-50 ${styles[variant]} ${className}`} {...props}>{children}</button>;
}

export function Card({ children, className = '' }) { return <section className={`rounded-2xl border border-navy-100/80 bg-white p-6 shadow-soft ${className}`}>{children}</section>; }
export function Badge({ children, tone = 'success' }) { const tones = { success: 'bg-emerald-50 text-success', warning: 'bg-amber-50 text-warning', danger: 'bg-red-50 text-danger', info: 'bg-navy-50 text-navy-700' }; return <span className={`inline-flex rounded-full px-3 py-1 text-sm font-bold ${tones[tone]}`}>{children}</span>; }
export function Input({ label, error, ...props }) { return <label className="block"><span className="mb-2 block font-bold text-ink">{label}</span><input className={`min-h-11 w-full rounded-lg border bg-white px-4 text-ink shadow-sm outline-none transition focus:border-teal-500 focus:ring-2 focus:ring-teal-100 ${error ? 'border-danger' : 'border-navy-100'}`} {...props} />{error && <span className="mt-1 block text-sm font-semibold text-danger">{error}</span>}</label>; }
export function Skeleton({ className = '' }) { return <div className={`animate-pulse rounded-lg bg-navy-50 ${className}`} />; }
export function EmptyState({ title, children }) { return <div className="rounded-xl border border-dashed border-navy-100 bg-navy-50/40 p-8 text-center"><p className="font-extrabold text-ink">{title}</p><p className="mt-1 text-navy-700">{children}</p></div>; }
export function Modal({ open, title, onClose, children }) { if (!open) return null; return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/40 p-4" role="dialog" aria-modal="true" aria-label={title}><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-extrabold">{title}</h2><button className="rounded-lg p-2 text-navy-700 hover:bg-navy-50" onClick={onClose} aria-label="Close dialog"><X size={22} /></button></div>{children}</div></div>; }
export function SearchBox({ value, onChange, placeholder = 'Search' }) { return <label className="relative block"><span className="sr-only">{placeholder}</span><Search className="absolute left-3 top-3 text-navy-500" size={20} /><input value={value} onChange={onChange} placeholder={placeholder} className="min-h-11 w-full rounded-lg border border-navy-100 bg-white pl-10 pr-4 outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100" /></label>; }
export function Loading({ label = 'Loading' }) { return <div className="flex items-center gap-2 text-navy-700"><LoaderCircle className="animate-spin" size={20} />{label}</div>; }
