import { ArrowUpRight, CalendarCheck2, CalendarPlus, ChevronRight, Clock3, FilePlus2, UsersRound, Activity } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { dashboardService } from '../api/dashboardService';
import { Badge, Button, Card } from '../components/ui';

const departmentColors = ['#179c91', '#397d9e', '#e3a33b', '#248b62'];
const roleCopy = {
  ADMIN: { title: 'Today at a glance', description: "Here is what needs your team's attention." },
  DOCTOR: { title: 'Your day at a glance', description: 'Your appointments and patient priorities are ready.' },
  RECEPTIONIST: { title: 'Keep the day moving', description: 'Bookings, arrivals and patient flow in one place.' },
};

function StatCard({ label, value, change, icon: Icon, tone }) {
  const toneClasses = { teal: 'bg-teal-100 text-teal-700', navy: 'bg-navy-100 text-navy-700', amber: 'bg-amber-100 text-warning', green: 'bg-emerald-100 text-success' };
  return <Card className="relative overflow-hidden"><div className={`mb-5 grid h-11 w-11 place-items-center rounded-xl ${toneClasses[tone]}`}><Icon size={23} /></div><p className="font-bold text-navy-700">{label}</p><div className="mt-1 flex items-end justify-between gap-3"><p className="text-3xl font-black text-ink">{value}</p><span className="text-right text-sm font-extrabold text-success">{change}</span></div></Card>;
}

export default function Dashboard() {
  const { user } = useAuth();
  const copy = roleCopy[user?.role] || roleCopy.ADMIN;
  const { stats, weeklyAppointments, departmentPatients, appointments } = dashboardService.getOverview(user?.role);
  return <div className="mx-auto max-w-[1500px] space-y-7">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-bold text-teal-700">Saturday, 19 September 2026</p><h2 className="mt-1 text-3xl font-black tracking-tight text-ink sm:text-4xl">{copy.title}</h2><p className="mt-2 text-navy-700">{copy.description}</p></div><Button><CalendarPlus size={19} />Book appointment</Button></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat) => <StatCard key={stat.label} {...stat} />)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.45fr_1fr]">
      <Card><div className="flex items-start justify-between"><div><h3 className="text-xl font-extrabold">Appointments this week</h3><p className="mt-1 text-sm text-navy-700">Completed and scheduled visits</p></div><Link to="/reports" className="font-extrabold text-teal-700">View report</Link></div><div className="mt-7 h-64 w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={weeklyAppointments} margin={{ top: 8, right: 4, left: -20, bottom: 0 }}><CartesianGrid stroke="#dcecf5" vertical={false} /><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: '#397d9e', fontSize: 13, fontWeight: 700 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#397d9e', fontSize: 12 }} /><Tooltip cursor={{ fill: '#effaf8' }} contentStyle={{ border: '1px solid #dcecf5', borderRadius: 12, fontWeight: 700 }} /><Bar dataKey="scheduled" name="Scheduled" fill="#179c91" radius={[6, 6, 0, 0]} /><Bar dataKey="completed" name="Completed" fill="#397d9e" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></Card>
      <Card><div className="flex items-start justify-between"><div><h3 className="text-xl font-extrabold">Patients by department</h3><p className="mt-1 text-sm text-navy-700">Current month</p></div><Activity className="text-teal-600" size={22} /></div><div className="mt-3 h-52 w-full"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={departmentPatients} dataKey="patients" nameKey="department" cx="50%" cy="50%" innerRadius={52} outerRadius={78} paddingAngle={3}>{departmentPatients.map((item, index) => <Cell key={item.department} fill={departmentColors[index % departmentColors.length]} />)}</Pie><Tooltip contentStyle={{ border: '1px solid #dcecf5', borderRadius: 12, fontWeight: 700 }} /></PieChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-3">{departmentPatients.map((item, index) => <div key={item.department} className="flex items-center gap-2 text-sm font-bold text-navy-700"><span className="h-3 w-3 rounded-full" style={{ backgroundColor: departmentColors[index % departmentColors.length] }} />{item.department}</div>)}</div></Card>
    </div>
    <Card><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h3 className="text-xl font-extrabold">Today&apos;s appointments</h3><p className="mt-1 text-sm text-navy-700">Your next scheduled patient visits</p></div><Link to="/appointments" className="inline-flex items-center gap-1 font-extrabold text-teal-700">See all appointments <ChevronRight size={18} /></Link></div><div className="mt-6 divide-y divide-navy-100">{appointments.map((appointment) => <div key={`${appointment.time}-${appointment.patient}`} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><span className="w-14 font-black text-navy-700">{appointment.time}</span><div><p className="font-extrabold">{appointment.patient}</p><p className="text-sm text-navy-700">{appointment.doctor} · {appointment.type}</p></div></div><div className="flex items-center gap-4 pl-[4.5rem] sm:pl-0"><Badge tone={appointment.status === 'Confirmed' ? 'success' : 'warning'}>{appointment.status}</Badge><button aria-label={`Open appointment for ${appointment.patient}`} className="rounded-lg p-2 text-navy-700 hover:bg-navy-50"><ArrowUpRight size={20} /></button></div></div>)}</div></Card>
    <div><h3 className="text-xl font-extrabold">Quick actions</h3><div className="mt-4 grid gap-4 sm:grid-cols-3"><Link to="/patients" className="group rounded-2xl border border-navy-100 bg-white p-5 shadow-soft transition hover:-translate-y-1 hover:border-teal-100"><span className="grid h-11 w-11 place-items-center rounded-xl bg-teal-100 text-teal-700"><FilePlus2 size={22} /></span><p className="mt-4 font-extrabold">Add patient</p><p className="mt-1 text-sm text-navy-700">Create a new patient record</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-extrabold text-teal-700">Open form <ChevronRight size={16} /></span></Link><Link to="/appointments" className="group rounded-2xl border border-navy-100 bg-white p-5 shadow-soft transition hover:-translate-y-1 hover:border-teal-100"><span className="grid h-11 w-11 place-items-center rounded-xl bg-navy-100 text-navy-700"><CalendarCheck2 size={22} /></span><p className="mt-4 font-extrabold">Book appointment</p><p className="mt-1 text-sm text-navy-700">Find an available time slot</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-extrabold text-teal-700">Start booking <ChevronRight size={16} /></span></Link><Link to="/doctors" className="group rounded-2xl border border-navy-100 bg-white p-5 shadow-soft transition hover:-translate-y-1 hover:border-teal-100"><span className="grid h-11 w-11 place-items-center rounded-xl bg-amber-100 text-warning"><UsersRound size={22} /></span><p className="mt-4 font-extrabold">View care team</p><p className="mt-1 text-sm text-navy-700">Check doctor availability</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-extrabold text-teal-700">Open directory <ChevronRight size={16} /></span></Link></div></div>
    <div className="flex items-center gap-2 text-sm text-navy-500"><Clock3 size={17} />Last updated just now</div>
  </div>;
}
